module.exports = {
  APIKEY: '79a225c51c6d412b8f7b50d22ae5f32c',
  VERSION: '1.0',
  QRCODE_RRE: 'https://',
  QRCODE_SUF: 'dytcV1.0',
  // BASE_URL: "https://cd.hengyefuyang.com/",
  BASE_URL: "http://localhost:8080/",
  USERID: "userId",
  TOKEN: "token",
  USER_IS_LOGIN: 'userIsLogion',
  USER_RE_LOGIN: 'userReLogin',
  USERPHONE: 'userPhone',
  IS_SHOW_GUID: 'isShowGuid',
  USERINFO: 'userInfo',
  USER_IS_BIND:'userIsBind',
  YINLIU_VAL: 'yinLiuVal',
  BANKS: 'banks',
  TIXIAN: 'TiXian',
  JIFENHUZHUAN: 'JiFenHuZhuan'
}